version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    groups:
      microsoft-packages:
        patterns:
          - "Microsoft.*"
      goodtocode-packages:
        patterns:
          - "Goodtocode.*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
    open-pull-requests-limit: 10
