env:
  rgEnvironment: COMPANY-rg-PRODUCT-001
  integrationPath: .
  integrationProject: '*.csproj'
  appcsConnection: ''
  appcsEnvironmentVariable: AZURE_APP_CONFIGURATION_CONNECTION
  stConnection: ''
  stEnvironmentVariable: AZURE_STORAGE_CONNECTION
jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: use .net 6.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: dotnet test
      run: dotnet test ${{ env. parameters.integrationPath  }}/**/${{ env. parameters.integrationProject  }}
      env:
        ${{ env. parameters.appcsEnvironmentVariable  }}: ${{ env. parameters.appcsConnection  }}
        ${{ env. parameters.stEnvironmentVariable  }}: ${{ env. parameters.stConnection  }}
        ASPNETCORE_ENVIRONMENT: ${{ env. parameters.rgEnvironment  }}
        AZURE_FUNCTIONS_ENVIRONMENT: ${{ env. parameters.rgEnvironment  }}
                    