name: 'Platform Hub IaC'

on:
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/COMPANY-platform-hub-iac.yml
      - .azure/**/*.bicep
      - .azure/**/*.bicepparams
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - .github/workflows/COMPANY-platform-hub-iac.yml
      - .azure/**/*.bicep
      - .azure/**/*.bicepparams
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run"
        required: true
        default: "development"

env:
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"
  
  # Hub Landing Zone
  PLATFORM_SUB_ID: "${{ secrets.PLATFORM_SUBSCRIPTION_ID }}"  
  HUB_LOCATION: "westus2"
  HUB_NETWORK_RG_NAME: "COMPANY-hubnetwork-plat-wus2-001-rg"
  HUB_NETWORK_BICEP_TEMPLATE: ".azure/templates/platform-hub-network-publicroute.bicep"
  HUB_NETWORK_BICEP_PARAMETERS: ".azure/variables/platform-hub-network-publicroute-plat.bicepparam"
  
  HUB_MGMT_RG_NAME: "COMPANY-hubmgmt-plat-wus2-001-rg"
  HUB_MGMT_BICEP_TEMPLATE: ".azure/templates/platform-hub-mgmt.bicep"
  HUB_MGMT_BICEP_PARAMETERS: ".azure/variables/platform-hub-mgmt-plat.bicepparam"
  
permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  ci:
    name: "Validate hub IaC"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PLATFORM_SUBSCRIPTION_ID }}

      - name: Create ${{ env.HUB_NETWORK_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az group create -n ${{ env.HUB_NETWORK_RG_NAME }} -l ${{ env.HUB_LOCATION }}

      - name: Validate ${{ env.HUB_NETWORK_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az deployment group what-if --resource-group ${{ env.HUB_NETWORK_RG_NAME }} --template-file ${{ env.HUB_NETWORK_BICEP_TEMPLATE }} --parameters ${{ env.HUB_NETWORK_BICEP_PARAMETERS }} --parameters hubMgmtSubscriptionId=${{ secrets.PLATFORM_SUBSCRIPTION_ID }} 

      - name: Create ${{ env.HUB_MGMT_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az group create -n ${{ env.HUB_MGMT_RG_NAME }} -l ${{ env.HUB_LOCATION }}

      - name: Validate ${{ env.HUB_MGMT_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az deployment group what-if --resource-group ${{ env.HUB_MGMT_RG_NAME }} --template-file ${{ env.HUB_MGMT_BICEP_TEMPLATE }} --parameters ${{ env.HUB_MGMT_BICEP_PARAMETERS }} --parameters hubMgmtSubscriptionId=${{ secrets.PLATFORM_SUBSCRIPTION_ID }} 

  cd:
    name: "Deploy landing zone IaC"
    runs-on: ubuntu-latest
    needs: ci
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PLATFORM_SUBSCRIPTION_ID }}

      - name: Create ${{ env.HUB_NETWORK_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az group create -n ${{ env.HUB_NETWORK_RG_NAME }} -l ${{ env.HUB_LOCATION }}

      - name: Validate ${{ env.HUB_NETWORK_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az deployment group create --resource-group ${{ env.HUB_NETWORK_RG_NAME }} --template-file ${{ env.HUB_NETWORK_BICEP_TEMPLATE }} --parameters ${{ env.HUB_NETWORK_BICEP_PARAMETERS }} --parameters hubMgmtSubscriptionId=${{ secrets.PLATFORM_SUBSCRIPTION_ID }} 

      - name: Create ${{ env.HUB_MGMT_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az group create -n ${{ env.HUB_MGMT_RG_NAME }} -l ${{ env.HUB_LOCATION }}

      - name: Validate ${{ env.HUB_MGMT_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az deployment group create --resource-group ${{ env.HUB_MGMT_RG_NAME }} --template-file ${{ env.HUB_MGMT_BICEP_TEMPLATE }} --parameters ${{ env.HUB_MGMT_BICEP_PARAMETERS }} --parameters hubMgmtSubscriptionId=${{ secrets.PLATFORM_SUBSCRIPTION_ID }} 
