name: 'Platform Spoke IaC'

on:
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/COMPANY-platform-spoke-iac.yml
      - .azure/**/*.bicep
      - .azure/**/*.bicepparams
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - .github/workflows/COMPANY-platform-spoke-iac.yml
      - .azure/**/*.bicep
      - .azure/**/*.bicepparams
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run"
        required: true
        default: "development"

env:
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"
  HUB_MGMT_RG_NAME: "COMPANY-hubmgmt-dev-wus2-001-rg"
  SPOKE_LOCATION: "westus2"
  SPOKE_NETWORK_RG_NAME: "COMPANY-spokenetwork-dev-wus2-001-rg"
  SPOKE_NETWORK_BICEP_TEMPLATE: ".azure/templates/platform-spoke-network-publicroute.bicep"
  SPOKE_NETWORK_BICEP_PARAMETERS: ".azure/variables/platform-spoke-network-publicroute-dev.bicepparam" 
  SPOKE_MGMT_RG_NAME: "COMPANY-spokemgmt-dev-wus2-001-rg"
  SPOKE_MGMT_BICEP_TEMPLATE: ".azure/templates/platform-spoke-mgmt.bicep"
  SPOKE_MGMT_BICEP_PARAMETERS: ".azure/variables/platform-spoke-mgmt-dev.bicepparam"
  
permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  ci:
    name: "Validate spoke IaC"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create ${{ env.SPOKE_NETWORK_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az group create -n ${{ env.SPOKE_NETWORK_RG_NAME }} -l ${{ env.SPOKE_LOCATION }}

      - name: Validate ${{ env.SPOKE_NETWORK_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az deployment group what-if --resource-group ${{ env.SPOKE_NETWORK_RG_NAME }} --template-file ${{ env.SPOKE_NETWORK_BICEP_TEMPLATE }} --parameters ${{ env.SPOKE_NETWORK_BICEP_PARAMETERS }}

      - name: Create ${{ env.SPOKE_MGMT_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az group create -n ${{ env.SPOKE_MGMT_RG_NAME }} -l ${{ env.SPOKE_LOCATION }}

      - name: Validate ${{ env.SPOKE_MGMT_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az deployment group what-if --resource-group ${{ env.SPOKE_MGMT_RG_NAME }} --template-file ${{ env.SPOKE_MGMT_BICEP_TEMPLATE }} --parameters ${{ env.SPOKE_MGMT_BICEP_PARAMETERS }} --parameters hubMgmtSubscriptionId=${{ secrets.PLATFORM_SUBSCRIPTION_ID }} hubMgmtResourceGroupName=${{ env.HUB_MGMT_RG_NAME }}

  cd:
    name: "Deploy landing zone IaC"
    runs-on: ubuntu-latest
    needs: ci
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create ${{ env.SPOKE_NETWORK_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az group create -n ${{ env.SPOKE_NETWORK_RG_NAME }} -l ${{ env.SPOKE_LOCATION }}

      - name: Deploy ${{ env.SPOKE_NETWORK_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az deployment group create --resource-group ${{ env.SPOKE_NETWORK_RG_NAME }} --template-file ${{ env.SPOKE_NETWORK_BICEP_TEMPLATE }} --parameters ${{ env.SPOKE_NETWORK_BICEP_PARAMETERS }}

      - name: Create ${{ env.SPOKE_MGMT_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az group create -n ${{ env.SPOKE_MGMT_RG_NAME }} -l ${{ env.SPOKE_LOCATION }}

      - name: Deploy ${{ env.SPOKE_MGMT_RG_NAME }}
        uses: Azure/cli@v2.1.0
        with:
          inlineScript: |
            az deployment group create --resource-group ${{ env.SPOKE_MGMT_RG_NAME }} --template-file ${{ env.SPOKE_MGMT_BICEP_TEMPLATE }} --parameters ${{ env.SPOKE_MGMT_BICEP_PARAMETERS }} --parameters hubMgmtSubscriptionId=${{ secrets.PLATFORM_SUBSCRIPTION_ID }} hubMgmtResourceGroupName=${{ env.HUB_MGMT_RG_NAME }}