name: 'API CI/CD'
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/COMPANY-PRODUCT-api.yml
      - src/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/COMPANY-PRODUCT-api.yml
      - src/**
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run"
        required: true
        default: "development"

permissions:
  id-token: write
  contents: read
  security-events: write

env:
  API_ARTIFACT_OUTPUT: 'publish_output'
  API_ARTIFACT_NAME: 'api-artifact'

jobs:
  ci:
    name: "API CI"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    environment: development
    strategy:
      matrix:
        DOTNET_VERSION: ["10.x"]
    env:
      SCRIPTS_PATH: "./.github/scripts"
      SRC_PATH: "./src"
      SRC_SLN: "COMPANY.PRODUCT.sln"
      API_PATH: "Presentation.WebApi"
      API_PROJECT: "Presentation.WebApi.csproj"
      TEST_PATH: "Tests.Specs.Integration"
      TEST_PROJECT: "Tests.Specs.Integration.csproj"
      RUNTIME_ENV: "Development"
      CONFIGURATION: "Release"
      VERSION_MAJOR: '1'
      VERSION_MINOR: '1'

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: dotnet version ${{ matrix.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.DOTNET_VERSION }}

      - name: Get Semantic Version
        id: get_version
        run: |
          $json = & "${{ env.SCRIPTS_PATH }}/ci/Get-Version.ps1" -Major ${{ env.VERSION_MAJOR }} -Minor ${{ env.VERSION_MINOR }} -Patch $env:GITHUB_RUN_NUMBER
          $versionObj = ($json | ConvertFrom-Json)
          echo "SEMANTIC_VERSION=$($versionObj.SemanticVersion)" >> $env:GITHUB_OUTPUT
          echo "FILE_VERSION=$($versionObj.FileVersion)" >> $env:GITHUB_OUTPUT
          echo "ASSEMBLY_VERSION=$($versionObj.AssemblyVersion)" >> $env:GITHUB_OUTPUT
          echo "INFORMATIONAL_VERSION=$($versionObj.InformationalVersion)" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Set-Version.ps1
        run: |
          $version = ${{ env.SCRIPTS_PATH }}/ci/Set-Version.ps1 -Path ${{ env.SRC_PATH }} -VersionToReplace 1.0.0 -Major ${{ env.VERSION_MAJOR }} -Minor ${{ env.VERSION_MINOR }} -Patch $env:GITHUB_RUN_NUMBER
          echo $version
          echo "VERSION=$version" >> $GITHUB_ENV
        shell: pwsh

      - name: pipeline environment configuration
        run: |
          echo "ASPNETCORE_ENVIRONMENT=${{ env.RUNTIME_ENV }}" >> $GITHUB_ENV
          echo "OpenAI:ApiKey=${{ secrets.OPENAI_APIKEY }}" >> $GITHUB_ENV
        shell: pwsh

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{ env.SRC_PATH }}/${{ env.API_PATH }}/appsettings.json, ${{ env.SRC_PATH }}/${{ env.API_PATH }}/appsettings.${{ env.RUNTIME_ENV }}.json, ${{ env.SRC_PATH }}/${{ env.TEST_PATH }}/appsettings.test.json'
        env: 
          OpenAI.ApiKey: ${{ secrets.OPENAI_APIKEY }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: csharp

      - name: Build
        run: |
          dotnet build ${{ env.SRC_PATH }}/${{ env.SRC_SLN }} --configuration ${{ env.CONFIGURATION }}
        shell: pwsh
       
      - name: Test
        run: |
          mkdir -p TestResults-${{ matrix.DOTNET_VERSION }}
          dotnet test ${{ env.SRC_PATH }}/${{ env.TEST_PATH }}/${{ env.TEST_PROJECT }} --configuration ${{ env.CONFIGURATION }} --results-directory TestResults-${{ matrix.DOTNET_VERSION }} --collect:"Code Coverage" --verbosity normal
        shell: pwsh

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ matrix.DOTNET_VERSION }}
          path: TestResults-${{ matrix.DOTNET_VERSION }}
        if: ${{ always() }}

      - name: Pack Web API artifact
        run: |
          dotnet publish ${{ env.SRC_PATH }}/${{ env.API_PATH }}/${{ env.API_PROJECT }} --configuration ${{ env.CONFIGURATION }} --no-build --output publish_output
        shell: pwsh

      - name: Upload Web API artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.API_ARTIFACT_NAME }}
          path: ${{ env.API_ARTIFACT_OUTPUT }}/**


      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        if: ${{ github.repository_visibility == 'public' }}

      - name: Run Coverage Script
        run: |
          pwsh ${{ env.SRC_PATH }}/Get-CodeCoverage.ps1 `
            -TestProjectFilter '${{ env.TEST_PROJECT }}' `
            -ProdPackagesOnly            
        shell: pwsh

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.DOTNET_VERSION }}
          path: ${{ env.SRC_PATH }}/TestResults/Reports/**/index.html
        if: ${{ always() }}

  cd:
    name: "API CD"
    runs-on: ubuntu-latest
    needs: ci
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main')
    environment: development
    strategy:
      matrix:
        DOTNET_VERSION: ["10.x"]
    env:
      SPOKE_RG_NAME: 'COMPANY-spokemgmt-dev-wus2-001-rg'
      APPI_NAME: 'spokemgmt-dev-wus2-001-appi'
      AZURE_APIAPP_NAME: PRODUCT-dev-wus2-001-api
      AZURE_RG_NAME: 'COMPANY-PRODUCT-dev-wus2-001-rg'
      RUNTIME_ENV: "Development"

    steps:
      - name: Download Web API artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.API_ARTIFACT_NAME }}
          path: ${{ env.API_ARTIFACT_OUTPUT }}

      - name: az login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Web API to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APIAPP_NAME }}
          package: ${{ env.API_ARTIFACT_OUTPUT }}


      - name: ${{ env.AZURE_APIAPP_NAME }} app settings
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
          $TEMP_JSON = az monitor app-insights component show -g ${{ env.SPOKE_RG_NAME }} --app ${{ env.APPI_NAME }} | ConvertFrom-Json
          $INSTR_KEY = $TEMP_JSON.instrumentationKey
          $CONN_STR = $TEMP_JSON.connectionString
          az webapp config appsettings set -g ${{ env.AZURE_RG_NAME }} -n ${{ env.AZURE_APIAPP_NAME }} --settings APPINSIGHTS_INSTRUMENTATIONKEY=$INSTR_KEY
          az webapp config appsettings set -g ${{ env.AZURE_RG_NAME }} -n ${{ env.AZURE_APIAPP_NAME }} --settings APPLICATIONINSIGHTS_CONNECTION_STRING=$CONN_STR
          az webapp config appsettings set -g ${{ env.AZURE_RG_NAME }} -n ${{ env.AZURE_APIAPP_NAME }} --settings ASPNETCORE_ENVIRONMENT=${{ env.RUNTIME_ENV }}
        shell: pwsh

      - name: Swap to production slot
        run: |
          az webapp deployment slot swap --resource-group ${{ env.AZURE_RG_NAME }} --name ${{ env.AZURE_APIAPP_NAME }} --slot staging --target-slot production
          echo "Swap finished. App Service Application URL: https://$(az webapp show --resource-group ${{ env.AZURE_RG_NAME }} --name ${{ env.AZURE_APIAPP_NAME }} --query hostNames[0] -o tsv)"
        if: ${{ false }}