name: CI/CD Build, Test and Deploy

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/COMPANY-rg-PRODUCT-ci-cd.yml
      - src/**
  push:
    branches:
    - main
    paths:
    - .github/workflows/COMPANY-rg-PRODUCT-ci-cd.yml
    - src/**
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run'
        required: true
        default: 'development'
      mode:
        description: 'Running mode'  

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  ci:
    name: 'CI Build, Test, Code QL, Publish'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    environment: development    
    strategy:
      matrix:
        DOTNET_VERSION: ['9.x']

    env:      
      RUNTIME_ENV: 'Development'
      SRC_PATH: './src'
      SRC_SLN: 'Goodtocode.Assertion.sln'      
      PROJECT_PATH: 'Goodtocode.Assertion'
      PROJECT_FILE: 'Goodtocode.Assertion.csproj'
      TEST_PATH: 'Tests.Unit'
      TEST_PROJECT: 'Tests.Unit.csproj'
      SCRIPTS_PATH: './.github/scripts'

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: dotnet version ${{ matrix.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.DOTNET_VERSION }}

      - name: Set-Version.ps1
        run: |
          $version = ${{ env.SCRIPTS_PATH }}/iac/Set-Version.ps1 -Path ${{ env.SRC_PATH }} -VersionToReplace 1.0.0
          echo $version
          echo "VERSION=$version" >> $GITHUB_ENV
        shell: pwsh

      - name: pipeline configuration secrets
        run: |
          echo "ASPNETCORE_ENVIRONMENT=${{ env.RUNTIME_ENV }}" >> $GITHUB_ENV
          echo "AZURE_FUNCTIONS_ENVIRONMENT=${{ env.RUNTIME_ENV }}" >> $GITHUB_ENV
          echo "OpenAI:ApiKey=${{ secrets.OPENAI_APIKEY }}" >> $GITHUB_ENV
        shell: pwsh

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{ env.SRC_PATH }}/${{ env.PROJECT_PATH }}/appsettings.json, ${{ env.SRC_PATH }}/${{ env.PROJECT_PATH }}/appsettings.${{ env.RUNTIME_ENV }}.json, ${{ env.SRC_PATH }}/${{ env.TEST_PATH }}/appsettings.test.json'
        env: 
          OpenAI.ApiKey: ${{ secrets.OPENAI_APIKEY }}
          
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
            
      - name: Build
        run: |
          dotnet build ${{ env.SRC_PATH }}/${{ env.SRC_SLN }} --configuration Release       
        shell: pwsh

      - name: Test
        run: |
          mkdir -p TestResults-${{ matrix.DOTNET_VERSION }}
          dotnet test ${{ env.SRC_PATH }}/${{ env.TEST_PATH }}/${{ env.TEST_PROJECT }} --logger "trx;LogFileName=test_results.trx" --results-directory TestResults-${{ matrix.DOTNET_VERSION }} --verbosity normal
        shell: pwsh

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ matrix.DOTNET_VERSION }}
          path: TestResults-${{ matrix.DOTNET_VERSION }}
        if: ${{ always() }}

      - name: Perform CodeQL Analysis 
        uses: github/codeql-action/analyze@v3

  cd:
    name: 'CD Pack and Publish to NuGet.org'
    runs-on: ubuntu-latest
    needs: ci
    if: |
      github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    environment: development
    strategy:
      matrix:
        DOTNET_VERSION: ['9.x']
    env:
      SRC_PATH: './src'
      PROJECT_PATH: 'Goodtocode.Assertion'
      PROJECT_FILE: 'Goodtocode.Assertion.csproj'
      NUGET_OUTPUT: 'nupkg_output'
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup .NET ${{ matrix.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.SRC_PATH }}/${{ env.PROJECT_PATH }}/${{ env.PROJECT_FILE }}

      - name: Build
        run: dotnet build ${{ env.SRC_PATH }}/${{ env.PROJECT_PATH }}/${{ env.PROJECT_FILE }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SRC_PATH }}/${{ env.PROJECT_PATH }}/${{ env.PROJECT_FILE }} --configuration Release --no-build --verbosity normal

      - name: Pack NuGet package
        run: dotnet pack ${{ env.SRC_PATH }}/${{ env.PROJECT_PATH }}/${{ env.PROJECT_FILE }} --configuration Release --no-build --output ${{ env.NUGET_OUTPUT }}

      - name: Publish to NuGet.org
        run: dotnet nuget push ${{ env.NUGET_OUTPUT }}/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}