name: api-deploy-steps.yml

on:
  workflow_call:
    inputs:
      artifactsPath:
        description: 'Path to pipeline artifacts - Default: github.workspace/artifacts'
        required: false
        type: string
        default: '${{ github.workspace }}/artifacts'
      archiveFile:
        description: 'Mask to artifact compressed filename - Default: *.zip'
        required: false
        type: string
        default: '*.zip'
      apiName:
        description: 'Name of the api- resource to deploy - Example: api-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string

    secrets:
      token:
        required: true

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - # "Note: the 'AZURE_SP' secret is required to be added into GitHub Secrets. See this blog post for details: https://samlearnsazure.blog/2019/12/13/github-actions/"
      name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    - uses: actions/download-artifact@v2
      with:
        name: drop
        path: ${{ github.event.inputs.artifactsPath  }}
    - name: deploy ${{ github.event.inputs.apiName  }}
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ github.event.inputs.apiName  }}
        package: ${{ github.event.inputs.artifactsPath  }}/**/${{ github.event.inputs.archiveFile  }}
                    