name: cog-infrastructure-steps.yml

on:
  workflow_call:
    inputs:
      armPath:
        description: 'Path to ARM *.json files - Example: ./infrastructure'
        required: true
        type: string
      rgName:
        description: 'Name of rg- Azure Resource Group - Example: COMPANY-rg-PRODUCT-001'
        required: true
        type: string
      rgLocation:
        description: 'Azure Region of the resource group - Example: westus2'
        required: true
        type: string
      cogName:
        description: 'Name of the cog- resource - Example: cog-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string
      cogSku:      
        description: 'Sku of the cog- resource - Example: S0'
        required: false
        type: choice
        default: 'S0'
        options:
          - 'S0'

    secrets:
      token:
        required: true

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - # "Note: the 'AZURE_SP' secret is required to be added into GitHub Secrets. See this blog post for details: https://samlearnsazure.blog/2019/12/13/github-actions/"
      name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    - name: Validate ${{ github.event.inputs.cogName  }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName  }} --template-file ${{ github.event.inputs.armPath  }}/cog-cognitiveservices.json --parameters  ${{ github.event.inputs.armPath  }}/cog-cognitiveservices.parameters.json -name "${{ github.event.inputs.cogName  }}" -sku "${{ github.event.inputs.cogSku  }}"
    - name: Validate ${{ github.event.inputs.cogtextName  }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName  }} --template-file ${{ github.event.inputs.armPath  }}/cogtext-textanalytics.json --parameters  ${{ github.event.inputs.armPath  }}/cogtext-textanalytics.parameters.json -name "${{ github.event.inputs.cogtextName  }}" -sku "${{ github.event.inputs.cogtextSku  }}"
                    