name: landingzone-infrastructure-steps.yml

on:
  workflow_call:
    inputs:
      armPath:
        description: 'Path to ARM *.json files - Example: ./infrastructure'
        required: true
        type: string
      rgName:
        description: 'Name of Azure Resource Group - Example: COMPANY-rg-PRODUCT-001'
        required: true
        type: string
      rgLocation:
        description: 'Azure Region of the resource group - Example: westus2'
        required: true
        type: string
      appiName:
        description: 'Key (guid) of the appi resource - Example: 00000000-0000-0000-0000-000000000000'
        required: true
        type: string
      appiConnection:
        description: 'Connection string of the appi resource - Example: InstrumentationKey=00000000-0000-0000-0000-000000000000;IngestionEndpoint=https://REGION.in.applicationinsights.azure.com...'
        required: true
        type: string
      rgEnvironment:
        description: 'Environment string of the Azure Resource Group - Default: Development'
        required: false
        type: string
        default: 'Development'
      funcName:
        description: 'Name of the func- resource to deploy - Example: func-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string
      funcVersion:
        description: 'Runtime Version of the func- resource to deploy - Example: 4'
        required: false
        type: string
        default: '4'
      stName:
        description: 'Name of the st- resource this func- resource depends - Example: stPRODUCTENVIRONMENT001'
        required: true
        type: string
      workName:
        description: 'Name of the work- resource this func- resource depends - Example: work-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string

env:
  armPath: .
  rgName: COMPANY-rg-PRODUCT-001
  rgLocation: West US 2
  appiName: appi-PRODUCT-ENVIRONMENT-001
  kvName: kv-PRODUCT-ENVIRONMENT-001
  stName: stPRODUCTENVIRONMENT001
  workName: work-PRODUCT-ENVIRONMENT-001
jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - # "Note: the 'AZURE_SP' secret is required to be added into GitHub Secrets. See this blog post for details: https://samlearnsazure.blog/2019/12/13/github-actions/"
      name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    - name: Validate ${{ github.event.inputs.stName   }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName  }} --template-file ${{ github.event.inputs.armPath  }}/st-storageaccount.json --parameters  ${{ github.event.inputs.armPath  }}/st-storageaccount.parameters.json -name "${{ github.event.inputs.stName   }}"
    - name: Deploy ${{ github.event.inputs.stName   }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName  }} --template-file ${{ github.event.inputs.armPath  }}/st-storageaccount.json --parameters  ${{ github.event.inputs.armPath  }}/st-storageaccount.parameters.json -name "${{ github.event.inputs.stName   }}"
    - name: Validate ${{ github.event.inputs.workName   }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName  }} --template-file ${{ github.event.inputs.armPath  }}/work-loganalyticsworkspace.json --parameters  ${{ github.event.inputs.armPath  }}/work-loganalyticsworkspace.parameters.json -name "${{ github.event.inputs.workName   }}"
    - name: Deploy ${{ github.event.inputs.workName   }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName  }} --template-file ${{ github.event.inputs.armPath  }}/work-loganalyticsworkspace.json --parameters  ${{ github.event.inputs.armPath  }}/work-loganalyticsworkspace.parameters.json -name "${{ github.event.inputs.workName   }}"
    - name: Validate ${{ github.event.inputs.appiName   }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName  }} --template-file ${{ github.event.inputs.armPath  }}/appi-applicationinsights.json --parameters  ${{ github.event.inputs.armPath  }}/appi-applicationinsights.parameters.json -name "${{ github.event.inputs.appiName   }}" -workName "${{ github.event.inputs.workName   }}"
    - name: Deploy ${{ github.event.inputs.appiName   }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName  }} --template-file ${{ github.event.inputs.armPath  }}/appi-applicationinsights.json --parameters  ${{ github.event.inputs.armPath  }}/appi-applicationinsights.parameters.json -name "${{ github.event.inputs.appiName   }}" -workName "${{ github.event.inputs.workName   }}"
    - name: Validate ${{ github.event.inputs.kvName   }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName  }} --template-file ${{ github.event.inputs.armPath  }}/kv-keyvault.json --parameters  ${{ github.event.inputs.armPath  }}/kv-keyvault.parameters.json -name "${{ github.event.inputs.kvName   }}"
    - name: Deploy ${{ github.event.inputs.kvName   }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName  }} --template-file ${{ github.event.inputs.armPath  }}/kv-keyvault.json --parameters  ${{ github.event.inputs.armPath  }}/kv-keyvault.parameters.json -name "${{ github.event.inputs.kvName   }}"
                    