env:
  artifactsPath: .
  srcPath: .
  scriptsPath: ./pipelines/scripts
jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Set-Version.ps1
      shell: powershell
      run: ${{ github.event.inputs.scriptsPath  }}/Set-Version.ps1 --Path ${{ github.event.inputs.srcPath  }} --VersionToReplace ${{ github.event.inputs.srcVersionToReplace  }}
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 17.x
    - name: npm install
      run: npm install ${{ github.event.inputs.srcPath  }}
    - name: npm run test
      run: npm run test ${{ github.event.inputs.srcPath  }}
    - name: 'Publish Artifact: drop'
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.event.inputs.artifactsPath  }}
        name: drop
                    