name: stblob-deploy-steps.yml

on:
  workflow_call:
    inputs:
      subscriptionId:
        description: 'Azure subscription id - Example: 00000000-0000-0000-0000-000000000000'
        required: true
        type: string
      destinationContainer:
        description: 'Name of the Azure Storage Container - Example: ingress'
        required: true
        type: string
      sourcePath:
        description: 'Path that contains the source files to copy to destination - Exmaple: github.workspace/files-for-storage'
        required: false
        type: string
      sourceFiles:
        description: 'Mask to the source files to copy to destination - Default: *'
        required: false
        type: string
        default: '*'
      arguments:
        description: 'Arguments for the source to destination copy operation - Default: *'
        required: false
        type: string
        default: '--overwrite true'
      stName:
        description: 'Name of the st- resource to deploy as destination - Example: stPRODUCTENVIRONMENT001'
        required: true
        type: string

    secrets:
      token:
        required: true

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - # "Note: the 'AZURE_SP' secret is required to be added into GitHub Secrets. See this blog post for details: https://samlearnsazure.blog/2019/12/13/github-actions/"
      name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    - # "Error: the step 'AzureFileCopy@4' does not have a conversion path yet"
      name: copy files to ${{ github.event.inputs.destinationContainer  }}
      run: |
        echo "Error: the step 'AzureFileCopy@4' does not have a conversion path yet"
        #task: AzureFileCopy@4
        #displayName: copy files to ${{ github.event.inputs.destinationContainer  }}
        #inputs:
        #  sourcepath: ${{ github.event.inputs.sourcePath  }}/${{ github.event.inputs.sourceFiles  }}
        #  azuresubscription: ${{ github.event.inputs.subscriptionId  }}
        #  destination: azureBlob
        #  storage: ${{ github.event.inputs.stName  }}
        #  destinationContainer: ${{ github.event.inputs.destinationContainer  }}
        #  additionalargumentsforblobcopy: ${{ github.event.inputs.arguments  }}
                    