#Note: the 'AZURE_SP' secret is required to be added into GitHub Secrets. See this blog post for details: https://samlearnsazure.blog/2019/12/13/github-actions/
env:
  armPath: .
  subscriptionId: 00000000-0000-0000-0000-000000000000
  subscriptionName: COMPANY-PRODUCT-001
  rgName: COMPANY-rg-PRODUCT-001
  rgLocation: West US 2
  rgEnvironment: Development
  planName: plan-webjob-PRODUCT-ENVIRONMENT-001
  planSku: F1
  webName: webjob-PRODUCT-ENVIRONMENT-001
jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - # "Note: the 'AZURE_SP' secret is required to be added into GitHub Secrets. See this blog post for details: https://samlearnsazure.blog/2019/12/13/github-actions/"
      name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    - name: Validate ${{ env. parameters.planName  }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ env. parameters.rgName  }} --template-file ${{ env. parameters.armPath  }}/plan-appplan.json --parameters  ${{ env. parameters.armPath  }}/plan-appplan.parameters.json -name "${{ env. parameters.planName  }}" -sku "${{ env. parameters.planSku  }}"
    - name: Deploy ${{ env. parameters.planName  }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ env. parameters.rgName  }} --template-file ${{ env. parameters.armPath  }}/plan-appplan.json --parameters  ${{ env. parameters.armPath  }}/plan-appplan.parameters.json -name "${{ env. parameters.planName  }}" -sku "${{ env. parameters.planSku  }}"
    - name: Validate ${{ env. parameters.webName  }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ env. parameters.rgName  }} --template-file ${{ env. parameters.armPath  }}/web-webapp.json --parameters  ${{ env. parameters.armPath  }}/web-webapp.parameters.json -name "${{ env. parameters.webName  }}" -planName "${{ env. parameters.planName  }}"
    - name: Deploy ${{ env. parameters.webName  }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ env. parameters.rgName  }} --template-file ${{ env. parameters.armPath  }}/web-webapp.json --parameters  ${{ env. parameters.armPath  }}/web-webapp.parameters.json -name "${{ env. parameters.webName  }}" -planName "${{ env. parameters.planName  }}"
                    