#Note: the 'AZURE_SP' secret is required to be added into GitHub Secrets. See this blog post for details: https://samlearnsazure.blog/2019/12/13/github-actions/
env:
  artifactsPath: .
  archiveFile: '*.zip'
  webName: web-PRODUCT-ENVIRONMENT-001
  subscriptionId: 00000000-0000-0000-0000-000000000000
  
jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - # "Note: the 'AZURE_SP' secret is required to be added into GitHub Secrets. See this blog post for details: https://samlearnsazure.blog/2019/12/13/github-actions/"
      name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}
    - uses: actions/download-artifact@v2
      with:
        name: drop
        path: ${{ github.event.inputs.artifactsPath  }}
    - name: Deploying ${{ github.event.inputs.webName  }}
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ github.event.inputs.webName  }}
        package: ${{ github.event.inputs.artifactsPath  }}/**/${{ github.event.inputs.archiveFile  }}
                    